name: Shell Commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest 
    steps:
      - name: echo a string
        run: echo "Hello Temedicans" 
      - name: multiline script
        run: | 
          node -v
          npm -v
# Upto Line 19, we were using default shell,which was bash. 
#In the below steps, we are going to use the python shell. Here we are just printing the processor of the machine
# To inform github actions, that we need to run it on python and not bash use shell:python as done below      
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python     
  run-windows-commands: #Created another job for windows. By default windows have powershell
    runs-on: windows-latest
    steps:
      - name: Directory Powershell
        run: Get-location
      - name: Directory bash #We can also use bash in Windows machine
        run: pwd
        shell: bash 