name: Using strategy

on: [push]

jobs:
  build:

    runs-on: ${{matrix.os}} #For running on multiple os
    strategy: 
      matrix: 
       os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
